/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RemontyRouteImport } from './routes/remonty'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as DyzainRouteImport } from './routes/dyzain'
import { Route as BudivnytstvoRouteImport } from './routes/budivnytstvo'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RemontyRoute = RemontyRouteImport.update({
  id: '/remonty',
  path: '/remonty',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const DyzainRoute = DyzainRouteImport.update({
  id: '/dyzain',
  path: '/dyzain',
  getParentRoute: () => rootRouteImport,
} as any)
const BudivnytstvoRoute = BudivnytstvoRouteImport.update({
  id: '/budivnytstvo',
  path: '/budivnytstvo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budivnytstvo': typeof BudivnytstvoRoute
  '/dyzain': typeof DyzainRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/remonty': typeof RemontyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budivnytstvo': typeof BudivnytstvoRoute
  '/dyzain': typeof DyzainRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/remonty': typeof RemontyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budivnytstvo': typeof BudivnytstvoRoute
  '/dyzain': typeof DyzainRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/remonty': typeof RemontyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budivnytstvo'
    | '/dyzain'
    | '/kontakty'
    | '/portfolio'
    | '/remonty'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budivnytstvo'
    | '/dyzain'
    | '/kontakty'
    | '/portfolio'
    | '/remonty'
    | '/robots.txt'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/budivnytstvo'
    | '/dyzain'
    | '/kontakty'
    | '/portfolio'
    | '/remonty'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudivnytstvoRoute: typeof BudivnytstvoRoute
  DyzainRoute: typeof DyzainRoute
  KontaktyRoute: typeof KontaktyRoute
  PortfolioRoute: typeof PortfolioRoute
  RemontyRoute: typeof RemontyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remonty': {
      id: '/remonty'
      path: '/remonty'
      fullPath: '/remonty'
      preLoaderRoute: typeof RemontyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dyzain': {
      id: '/dyzain'
      path: '/dyzain'
      fullPath: '/dyzain'
      preLoaderRoute: typeof DyzainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budivnytstvo': {
      id: '/budivnytstvo'
      path: '/budivnytstvo'
      fullPath: '/budivnytstvo'
      preLoaderRoute: typeof BudivnytstvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudivnytstvoRoute: BudivnytstvoRoute,
  DyzainRoute: DyzainRoute,
  KontaktyRoute: KontaktyRoute,
  PortfolioRoute: PortfolioRoute,
  RemontyRoute: RemontyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
